# Generated by Django 6.0.6 on 2026-07-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
