# Generated by Django 6.0.6 on 2026-07-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_song_title'),
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(related_name='songs', to='playlists.playlist'),
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
